#!/bin/sh
echo $1
#zathura -x "gvim --servername $1 -c \"let g:syncpdf='$2'\" --remote +%{line} %{input}" $2
env GTK_MODULES= /usr/bin/zathura -x "gvim --servername $1 -c \"let g:syncpdf='$2'\" --remote +%{line} %{input}" $2
